---
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/lib/grafana/plugins/briangann-circleci-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_LOG_FILTERS=plugins:debug
      - GF_DATAPROXY_LOGGING=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=briangann-circleci-datasource
